### ISSUE TITLE
stackoverflow

### ISSUE THREAD

**Issue by fabianHAW** [Dutzel/TTV-Lab2#17]
irgendwie bekommen wir nach gewisser zeit einen stackoverflow:

`Exception in thread "Thread-1" java.lang.StackOverflowError
	at java.lang.Class.getEnclosingMethodInfo(Class.java:1072)
	at java.lang.Class.getEnclosingClass(Class.java:1272)
	at java.lang.Class.getSimpleBinaryName(Class.java:1443)
	at java.lang.Class.getSimpleName(Class.java:1309)
	at de.uniba.wiai.lspi.chord.com.Node.toString(Node.java:73)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
....`

der tritt auch immer an einer anderen stelle im code auf. 
eine idee ist, dass wir mal den zugewiesenen speicher für die jvm höher schrauben. das geht bei eclipse irgendwie..erste suche ergab: https://wiki.eclipse.org/FAQ_How_do_I_increase_the_heap_size_available_to_Eclipse%3F

**Comment by fabianHAW** [comment]
aktueller commit c95c1096c5fc984d82fbffebaa7f5d2e3bfc2383 läuft bei synchroner broadcast kommunkation ohne probleme durch bei 4 spielern. problem ist die heapsize wie schon im kommentar zuvor beschrieben. wird anwendung mit 4 spielern und asynchroner kommunikation gestartet, gibt es weiterhin stackoverflows. um dem zu begegnen: maximale heap size hochdrehen. in der "eclipse.ini" kann der parameter "-Xmx1024m" (default bei mir) erhöht werden: "-Xmx1512m" tats bereits. 

daher ist issue hiermit gefixed..
